export default {
  UserName: 'Name',
  ChangePassword: 'Change Password ?',
  Password: 'Password',
  PlaceholderOldpwd: 'Old Password',
  PlaceholderNewpwd: 'New Password',
  PlaceholderConpwd: 'Confirm Password',
  Email: 'Email',

  PlaceholderMob: 'Mobile',
  PlaceholderOTP: 'OTP',
  Presenter: 'Presenter',
  Enroll: 'ENROLL',
  Participant: 'Participant',
  pay: 'Pay',
  OralPresentation: 'Oral Presentation',
  PosterPresentation: 'Poster Presentation',
  VirtualPresentation: 'Virtual Presentation',
  submitAbstract: 'Submit Abstract',
  submitLater: 'Submit Later',
  submit: 'Submit',
  checkout: 'Checkout',

  BtnResendOTP: 'Resend OTP',
  BtnSendOTP: 'Send OTP',
  BtnCancel: 'Cancel',
  BtnSave: 'Save',
  BtnNEXT: 'NEXT',
  BtnSEND: 'SEND',
  BtnSubmit: 'Submit',
  BtnChectout: 'Checkout',
  AccManagement: 'Account Management',
  Url: 'url',
  textvalue: 'text',
  button_text: 'btn',
  msg: 'msg',
  pass: 'pass',
  Wrong: 'wrong',
};
